import img1 from "./assets/visa.png";
import img2 from "./assets/visaelectron.png";
import img3 from "./assets/mastercard.png";
import img4 from "./assets/maestro.png";
import img5 from "./assets/Americanexpress.png";
import img6 from "./assets/Diners-Club.png";
import img7 from "./assets/Paytm.jpg";
import img8 from "./assets/Upi.png";
import img9 from "./assets/JCB_logo.svg.webp";
import img10 from "./assets/discover-card4683.jpg";
export { img1, img2, img3, img4, img5, img6, img7, img8, img9, img10 };
